{-# LANGUAGE Arrows #-}
{-# LANGUAGE RecordWildCards #-}
{-# LANGUAGE PartialTypeSignatures #-}

module Selector where
import TORCS
import FRP.Yampa

import SettingType
import FunctionDefs

-- option to send a (Double,Int) to Int
selectFromCaseDII c targetSpeed = proc CarState{..} -> do
  outSig <- 
    case c of
	Setting "shifting" "(angle,gear')" -> arr shifting -< (angle,gear')
	Setting "shifting" "(trackPos,gear')" -> arr shifting -< (trackPos,gear')
	Setting "shifting" "(speedY,gear')" -> arr shifting -< (speedY,gear')
	Setting "shifting" "(speedX,gear')" -> arr shifting -< (speedX,gear')
	Setting "shifting" "(speedZ,gear')" -> arr shifting -< (speedZ,gear')
	Setting "shifting" "(rpm,gear')" -> arr shifting -< (rpm,gear')
        _ -> constant 0 -< ()
  returnA -< outSig

--options to send a (Double,Double) -> Double
selectFromCaseDDD c targetSpeed = proc CarState{..} -> do
  outSig <- 
    case c of
	Setting "steering" "(angle,trackPos)" -> arr steering -< (angle,trackPos)
	Setting "steering" "(angle,speedY)" -> arr steering -< (angle,speedY)
	Setting "steering" "(angle,speedX)" -> arr steering -< (angle,speedX)
	Setting "steering" "(angle,speedZ)" -> arr steering -< (angle,speedZ)
	Setting "steering" "(angle,rpm)" -> arr steering -< (angle,rpm)
	Setting "steering" "(trackPos,angle)" -> arr steering -< (trackPos,angle)
	Setting "steering" "(trackPos,trackPos)" -> arr steering -< (trackPos,trackPos)
	Setting "steering" "(trackPos,speedY)" -> arr steering -< (trackPos,speedY)
	Setting "steering" "(trackPos,speedX)" -> arr steering -< (trackPos,speedX)
	Setting "steering" "(trackPos,speedZ)" -> arr steering -< (trackPos,speedZ)
	Setting "steering" "(trackPos,rpm)" -> arr steering -< (trackPos,rpm)
	Setting "steering" "(speedY,angle)" -> arr steering -< (speedY,angle)
	Setting "steering" "(speedY,trackPos)" -> arr steering -< (speedY,trackPos)
	Setting "steering" "(speedY,speedY)" -> arr steering -< (speedY,speedY)
	Setting "steering" "(speedY,speedX)" -> arr steering -< (speedY,speedX)
	Setting "steering" "(speedY,speedZ)" -> arr steering -< (speedY,speedZ)
	Setting "steering" "(speedY,rpm)" -> arr steering -< (speedY,rpm)
	Setting "steering" "(speedX,angle)" -> arr steering -< (speedX,angle)
	Setting "steering" "(speedX,trackPos)" -> arr steering -< (speedX,trackPos)
	Setting "steering" "(speedX,speedY)" -> arr steering -< (speedX,speedY)
	Setting "steering" "(speedX,speedX)" -> arr steering -< (speedX,speedX)
	Setting "steering" "(speedX,speedZ)" -> arr steering -< (speedX,speedZ)
	Setting "steering" "(speedX,rpm)" -> arr steering -< (speedX,rpm)
	Setting "steering" "(speedZ,angle)" -> arr steering -< (speedZ,angle)
	Setting "steering" "(speedZ,trackPos)" -> arr steering -< (speedZ,trackPos)
	Setting "steering" "(speedZ,speedY)" -> arr steering -< (speedZ,speedY)
	Setting "steering" "(speedZ,speedX)" -> arr steering -< (speedZ,speedX)
	Setting "steering" "(speedZ,speedZ)" -> arr steering -< (speedZ,speedZ)
	Setting "steering" "(speedZ,rpm)" -> arr steering -< (speedZ,rpm)
	Setting "steering" "(rpm,angle)" -> arr steering -< (rpm,angle)
	Setting "steering" "(rpm,trackPos)" -> arr steering -< (rpm,trackPos)
	Setting "steering" "(rpm,speedY)" -> arr steering -< (rpm,speedY)
	Setting "steering" "(rpm,speedX)" -> arr steering -< (rpm,speedX)
	Setting "steering" "(rpm,speedZ)" -> arr steering -< (rpm,speedZ)
	Setting "steering" "(rpm,rpm)" -> arr steering -< (rpm,rpm)
	Setting "(gas targetSpeed)" "(angle,angle)" -> arr (gas targetSpeed) -< (angle,angle)
	Setting "(gas targetSpeed)" "(angle,trackPos)" -> arr (gas targetSpeed) -< (angle,trackPos)
	Setting "(gas targetSpeed)" "(angle,speedY)" -> arr (gas targetSpeed) -< (angle,speedY)
	Setting "(gas targetSpeed)" "(angle,speedX)" -> arr (gas targetSpeed) -< (angle,speedX)
	Setting "(gas targetSpeed)" "(angle,speedZ)" -> arr (gas targetSpeed) -< (angle,speedZ)
	Setting "(gas targetSpeed)" "(angle,rpm)" -> arr (gas targetSpeed) -< (angle,rpm)
	Setting "(gas targetSpeed)" "(trackPos,angle)" -> arr (gas targetSpeed) -< (trackPos,angle)
	Setting "(gas targetSpeed)" "(trackPos,trackPos)" -> arr (gas targetSpeed) -< (trackPos,trackPos)
	Setting "(gas targetSpeed)" "(trackPos,speedY)" -> arr (gas targetSpeed) -< (trackPos,speedY)
	Setting "(gas targetSpeed)" "(trackPos,speedX)" -> arr (gas targetSpeed) -< (trackPos,speedX)
	Setting "(gas targetSpeed)" "(trackPos,speedZ)" -> arr (gas targetSpeed) -< (trackPos,speedZ)
	Setting "(gas targetSpeed)" "(trackPos,rpm)" -> arr (gas targetSpeed) -< (trackPos,rpm)
	Setting "(gas targetSpeed)" "(speedY,angle)" -> arr (gas targetSpeed) -< (speedY,angle)
	Setting "(gas targetSpeed)" "(speedY,trackPos)" -> arr (gas targetSpeed) -< (speedY,trackPos)
	Setting "(gas targetSpeed)" "(speedY,speedY)" -> arr (gas targetSpeed) -< (speedY,speedY)
	Setting "(gas targetSpeed)" "(speedY,speedX)" -> arr (gas targetSpeed) -< (speedY,speedX)
	Setting "(gas targetSpeed)" "(speedY,speedZ)" -> arr (gas targetSpeed) -< (speedY,speedZ)
	Setting "(gas targetSpeed)" "(speedY,rpm)" -> arr (gas targetSpeed) -< (speedY,rpm)
	Setting "(gas targetSpeed)" "(speedX,angle)" -> arr (gas targetSpeed) -< (speedX,angle)
	Setting "(gas targetSpeed)" "(speedX,trackPos)" -> arr (gas targetSpeed) -< (speedX,trackPos)
	Setting "(gas targetSpeed)" "(speedX,speedY)" -> arr (gas targetSpeed) -< (speedX,speedY)
	Setting "(gas targetSpeed)" "(speedX,speedX)" -> arr (gas targetSpeed) -< (speedX,speedX)
	Setting "(gas targetSpeed)" "(speedX,speedZ)" -> arr (gas targetSpeed) -< (speedX,speedZ)
	Setting "(gas targetSpeed)" "(speedX,rpm)" -> arr (gas targetSpeed) -< (speedX,rpm)
	Setting "(gas targetSpeed)" "(speedZ,angle)" -> arr (gas targetSpeed) -< (speedZ,angle)
	Setting "(gas targetSpeed)" "(speedZ,trackPos)" -> arr (gas targetSpeed) -< (speedZ,trackPos)
	Setting "(gas targetSpeed)" "(speedZ,speedY)" -> arr (gas targetSpeed) -< (speedZ,speedY)
	Setting "(gas targetSpeed)" "(speedZ,speedX)" -> arr (gas targetSpeed) -< (speedZ,speedX)
	Setting "(gas targetSpeed)" "(speedZ,speedZ)" -> arr (gas targetSpeed) -< (speedZ,speedZ)
	Setting "(gas targetSpeed)" "(speedZ,rpm)" -> arr (gas targetSpeed) -< (speedZ,rpm)
	Setting "(gas targetSpeed)" "(rpm,angle)" -> arr (gas targetSpeed) -< (rpm,angle)
	Setting "(gas targetSpeed)" "(rpm,trackPos)" -> arr (gas targetSpeed) -< (rpm,trackPos)
	Setting "(gas targetSpeed)" "(rpm,speedY)" -> arr (gas targetSpeed) -< (rpm,speedY)
	Setting "(gas targetSpeed)" "(rpm,speedX)" -> arr (gas targetSpeed) -< (rpm,speedX)
	Setting "(gas targetSpeed)" "(rpm,speedZ)" -> arr (gas targetSpeed) -< (rpm,speedZ)
	Setting "(gas targetSpeed)" "(rpm,rpm)" -> arr (gas targetSpeed) -< (rpm,rpm)
        _ -> constant 0 -< ()
  returnA -< outSig


--options to send a (Double,Double) -> Double including piping prev computed value 's'
selectFromCaseDDDPrev c targetSpeed = proc (CarState{..},s) -> do
  outSig <- 
    case c of
	Setting "steering" "(angle,angle)" -> arr steering -< (angle,angle)
	Setting "steering" "(angle,trackPos)" -> arr steering -< (angle,trackPos)
	Setting "steering" "(angle,speedY)" -> arr steering -< (angle,speedY)
	Setting "steering" "(angle,speedX)" -> arr steering -< (angle,speedX)
	Setting "steering" "(angle,speedZ)" -> arr steering -< (angle,speedZ)
	Setting "steering" "(angle,rpm)" -> arr steering -< (angle,rpm)
	Setting "steering" "(trackPos,angle)" -> arr steering -< (trackPos,angle)
	Setting "steering" "(trackPos,trackPos)" -> arr steering -< (trackPos,trackPos)
	Setting "steering" "(trackPos,speedY)" -> arr steering -< (trackPos,speedY)
	Setting "steering" "(trackPos,speedX)" -> arr steering -< (trackPos,speedX)
	Setting "steering" "(trackPos,speedZ)" -> arr steering -< (trackPos,speedZ)
	Setting "steering" "(trackPos,rpm)" -> arr steering -< (trackPos,rpm)
	Setting "steering" "(speedY,angle)" -> arr steering -< (speedY,angle)
	Setting "steering" "(speedY,trackPos)" -> arr steering -< (speedY,trackPos)
	Setting "steering" "(speedY,speedY)" -> arr steering -< (speedY,speedY)
	Setting "steering" "(speedY,speedX)" -> arr steering -< (speedY,speedX)
	Setting "steering" "(speedY,speedZ)" -> arr steering -< (speedY,speedZ)
	Setting "steering" "(speedY,rpm)" -> arr steering -< (speedY,rpm)
	Setting "steering" "(speedX,angle)" -> arr steering -< (speedX,angle)
	Setting "steering" "(speedX,trackPos)" -> arr steering -< (speedX,trackPos)
	Setting "steering" "(speedX,speedY)" -> arr steering -< (speedX,speedY)
	Setting "steering" "(speedX,speedX)" -> arr steering -< (speedX,speedX)
	Setting "steering" "(speedX,speedZ)" -> arr steering -< (speedX,speedZ)
	Setting "steering" "(speedX,rpm)" -> arr steering -< (speedX,rpm)
	Setting "steering" "(speedZ,angle)" -> arr steering -< (speedZ,angle)
	Setting "steering" "(speedZ,trackPos)" -> arr steering -< (speedZ,trackPos)
	Setting "steering" "(speedZ,speedY)" -> arr steering -< (speedZ,speedY)
	Setting "steering" "(speedZ,speedX)" -> arr steering -< (speedZ,speedX)
	Setting "steering" "(speedZ,speedZ)" -> arr steering -< (speedZ,speedZ)
	Setting "steering" "(speedZ,rpm)" -> arr steering -< (speedZ,rpm)
	Setting "steering" "(rpm,angle)" -> arr steering -< (rpm,angle)
	Setting "steering" "(rpm,trackPos)" -> arr steering -< (rpm,trackPos)
	Setting "steering" "(rpm,speedY)" -> arr steering -< (rpm,speedY)
	Setting "steering" "(rpm,speedX)" -> arr steering -< (rpm,speedX)
	Setting "steering" "(rpm,speedZ)" -> arr steering -< (rpm,speedZ)
	Setting "steering" "(rpm,rpm)" -> arr steering -< (rpm,rpm)
	Setting "(gas targetSpeed)" "(angle,angle)" -> arr (gas targetSpeed) -< (angle,angle)
	Setting "(gas targetSpeed)" "(angle,trackPos)" -> arr (gas targetSpeed) -< (angle,trackPos)
	Setting "(gas targetSpeed)" "(angle,speedY)" -> arr (gas targetSpeed) -< (angle,speedY)
	Setting "(gas targetSpeed)" "(angle,speedX)" -> arr (gas targetSpeed) -< (angle,speedX)
	Setting "(gas targetSpeed)" "(angle,speedZ)" -> arr (gas targetSpeed) -< (angle,speedZ)
	Setting "(gas targetSpeed)" "(angle,rpm)" -> arr (gas targetSpeed) -< (angle,rpm)
	Setting "(gas targetSpeed)" "(trackPos,angle)" -> arr (gas targetSpeed) -< (trackPos,angle)
	Setting "(gas targetSpeed)" "(trackPos,trackPos)" -> arr (gas targetSpeed) -< (trackPos,trackPos)
	Setting "(gas targetSpeed)" "(trackPos,speedY)" -> arr (gas targetSpeed) -< (trackPos,speedY)
	Setting "(gas targetSpeed)" "(trackPos,speedX)" -> arr (gas targetSpeed) -< (trackPos,speedX)
	Setting "(gas targetSpeed)" "(trackPos,speedZ)" -> arr (gas targetSpeed) -< (trackPos,speedZ)
	Setting "(gas targetSpeed)" "(trackPos,rpm)" -> arr (gas targetSpeed) -< (trackPos,rpm)
	Setting "(gas targetSpeed)" "(speedY,angle)" -> arr (gas targetSpeed) -< (speedY,angle)
	Setting "(gas targetSpeed)" "(speedY,trackPos)" -> arr (gas targetSpeed) -< (speedY,trackPos)
	Setting "(gas targetSpeed)" "(speedY,speedY)" -> arr (gas targetSpeed) -< (speedY,speedY)
	Setting "(gas targetSpeed)" "(speedY,speedX)" -> arr (gas targetSpeed) -< (speedY,speedX)
	Setting "(gas targetSpeed)" "(speedY,speedZ)" -> arr (gas targetSpeed) -< (speedY,speedZ)
	Setting "(gas targetSpeed)" "(speedY,rpm)" -> arr (gas targetSpeed) -< (speedY,rpm)
	Setting "(gas targetSpeed)" "(speedX,angle)" -> arr (gas targetSpeed) -< (speedX,angle)
	Setting "(gas targetSpeed)" "(speedX,trackPos)" -> arr (gas targetSpeed) -< (speedX,trackPos)
	Setting "(gas targetSpeed)" "(speedX,speedY)" -> arr (gas targetSpeed) -< (speedX,speedY)
	Setting "(gas targetSpeed)" "(speedX,speedX)" -> arr (gas targetSpeed) -< (speedX,speedX)
	Setting "(gas targetSpeed)" "(speedX,speedZ)" -> arr (gas targetSpeed) -< (speedX,speedZ)
	Setting "(gas targetSpeed)" "(speedX,rpm)" -> arr (gas targetSpeed) -< (speedX,rpm)
	Setting "(gas targetSpeed)" "(speedZ,angle)" -> arr (gas targetSpeed) -< (speedZ,angle)
	Setting "(gas targetSpeed)" "(speedZ,trackPos)" -> arr (gas targetSpeed) -< (speedZ,trackPos)
	Setting "(gas targetSpeed)" "(speedZ,speedY)" -> arr (gas targetSpeed) -< (speedZ,speedY)
	Setting "(gas targetSpeed)" "(speedZ,speedX)" -> arr (gas targetSpeed) -< (speedZ,speedX)
	Setting "(gas targetSpeed)" "(speedZ,speedZ)" -> arr (gas targetSpeed) -< (speedZ,speedZ)
	Setting "(gas targetSpeed)" "(speedZ,rpm)" -> arr (gas targetSpeed) -< (speedZ,rpm)
	Setting "(gas targetSpeed)" "(rpm,angle)" -> arr (gas targetSpeed) -< (rpm,angle)
	Setting "(gas targetSpeed)" "(rpm,trackPos)" -> arr (gas targetSpeed) -< (rpm,trackPos)
	Setting "(gas targetSpeed)" "(rpm,speedY)" -> arr (gas targetSpeed) -< (rpm,speedY)
	Setting "(gas targetSpeed)" "(rpm,speedX)" -> arr (gas targetSpeed) -< (rpm,speedX)
	Setting "(gas targetSpeed)" "(rpm,speedZ)" -> arr (gas targetSpeed) -< (rpm,speedZ)
	Setting "(gas targetSpeed)" "(rpm,rpm)" -> arr (gas targetSpeed) -< (rpm,rpm)
	Setting "steering" "(angle,s)" -> arr steering -< (angle,s)
	Setting "steering" "(trackPos,s)" -> arr steering -< (trackPos,s)
	Setting "steering" "(speedY,s)" -> arr steering -< (speedY,s)
	Setting "steering" "(speedX,s)" -> arr steering -< (speedX,s)
	Setting "steering" "(speedZ,s)" -> arr steering -< (speedZ,s)
	Setting "steering" "(rpm,s)" -> arr steering -< (rpm,s)
	Setting "(gas targetSpeed)" "(angle,s)" -> arr (gas targetSpeed) -< (angle,s)
	Setting "(gas targetSpeed)" "(trackPos,s)" -> arr (gas targetSpeed) -< (trackPos,s)
	Setting "(gas targetSpeed)" "(speedY,s)" -> arr (gas targetSpeed) -< (speedY,s)
	Setting "(gas targetSpeed)" "(speedX,s)" -> arr (gas targetSpeed) -< (speedX,s)
	Setting "(gas targetSpeed)" "(speedZ,s)" -> arr (gas targetSpeed) -< (speedZ,s)
	Setting "(gas targetSpeed)" "(rpm,s)" -> arr (gas targetSpeed) -< (rpm,s)
	_ -> constant 0 -< ()
  returnA -< outSig

